export const fieldsMapping = () => {
    return {
        qf: 'First Name',
        qn: 'Last Name',
        qfalias: 'Alias First Name',
        qmalias: 'Alias Middle Name',
        qnalias: 'Alias Last Name',
        qdob: 'Date of birth',
        qmi: 'Middle Name',
        qnomi: 'No Middle Name',
        qmf : 'Gender',
        qobirth : 'Birth Country',
        qsbirth : 'Birth City',
        qcbirth : 'Birth State',
        qee : 'Email',
        qjobposition : 'Job Position',
        qphone: 'Phone',
        qo : 'Country',
        qa : 'Address',
        qc : 'City',
        qs : 'State',
        qz : 'Zip',
        qresfromdate : 'Resided From',
        qrestodate : 'Resided To',
        qcanadaidverification : 'ID Verification Type',
        qofframpidverification : 'Off Ramp ID Verification Type',
        qhaveconviction : 'Have Conviction?',
        qconvictedoffence : 'Convicted Offense',
        qdateconviction : 'Date of Conviction'
    };
};